#!/bin/bash

JQUERY="3.6.0"
BOOTSTRAP="5.1.3"

# jQuery
wget -O js/jquery-$JQUERY.min.js https://code.jquery.com/jquery-$JQUERY.min.js
get commit -m "updated jquery to $JQUERY" js/jquery-$JQUERY.min.js

# Bootstrap
mkdir .bootstrap && cd .bootstrap
wget https://github.com/twbs/bootstrap/releases/download/v$BOOTSTRAP/bootstrap-$BOOTSTRAP-dist.zip
unzip bootstrap-$BOOTSTRAP-dist.zip
cp bootstrap-$BOOTSTRAP-dist/css/bootstrap.min.css* ../css/
cp bootstrap-$BOOTSTRAP-dist/js/bootstrap.min.js* ../js/
cd ..
rm -rf .bootstrap
git commit -m "updated bootstrap to $BOOTSTRAP" css/bootstrap.min.css* js/bootstrap.min.js*

# jQuery Typeahead
mkdir .typeahead && cd .typeahead
wget https://github.com/running-coder/jquery-typeahead/archive/refs/heads/master.zip
unzip master.zip
cp jquery-typeahead-master/src/jquery.typeahead.css ../css/
cp jquery-typeahead-master/src/jquery.typeahead.js ../js/
cd ..
rm -rf .typeahead
git commit -m "updated typeahead" css/jquery.typeahead* js/jquery.typeahead*
